dist: trusty
sudo: required
language: cpp
compiler:
- clang

before_install:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/usr/local/lib
  - sudo apt-get install -y bison flex check libjson-c-dev uuid-dev libstdc++-4.8-dev autoconf-archive astyle
  - sudo apt-get build-dep libxen-dev
  - sudo dpkg -i test-packages/xentools_4.7-drakvuf1-1_amd64.deb
  - sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.so /usr/lib/x86_64-linux-gnu/libstdc++.so
  - git submodule init
  - git submodule update libvmi
  - cd libvmi && ./autogen.sh && ./configure --enable-xen --disable-kvm --without-xenstore
  - make && sudo make install
  - cd ..

install:
  - git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
  - git fetch upstream

script:
  - git diff --check upstream/master
  - export ARTISTIC_STYLE_OPTIONS=".astylerc" && astyle `find src | egrep "\.c|\.h"` > astyle.out && git --no-pager diff
  - TEST=$(cat astyle.out | grep Formatted | wc -l) && if [ $TEST -ne 0 ]; then echo "Please fix style issues as shown above" && exit 1; fi
  - ./autogen.sh
  - ./configure --enable-debug
  - make

git:
  submodules: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ZkXc5huudqMN0PXeloNfnuwaq4PQ6BDmU1Ov/ONDOtnwxkm4hxHrbbPwZ9O7/DprAor9p7X7jhx6sf3fsMB+ib0ARffQPB0JQNPPEWjbgUhTLL//y0W64efuwSrRLfaHXbcm6OJT1pjeyXWOKOMPrM7GBOnnRRscpDNtjqriPAs="

addons:
  coverity_scan:
    project:
      name: "tklengyel/drakvuf"
      description: "Build submitted via Travis CI"
    notification_email: tamas.k.lengyel@gmail.com
    build_command_prepend: "./autogen.sh; ./configure; make clean"
    build_command:   "make"
    branch_pattern: staging
